import { writeFileSync, existsSync } from "fs";
import { join } from "path";
import { loadSchema } from "../../utils/schema-loader.js";

export async function generateCommand() {
  let schema;
  try {
    schema = await loadSchema();
  } catch (err) {
    console.error("\x1b[31m%s\x1b[0m", (err as Error).message);
    process.exit(1);
  }

  const examplePath = join(process.cwd(), ".env.example");

  let content = "# Generated by Venvy\n\n";
  for (const [key, validator] of Object.entries(schema)) {
    const defaultValue = (validator as any)._default;
    if (defaultValue !== undefined) {
      content += `${key}=${defaultValue}\n`;
    } else {
      content += `${key}=\n`;
    }
  }

  writeFileSync(examplePath, content);
  console.log("\x1b[32m%s\x1b[0m", "Successfully generated .env.example");
}
